{% set name = "pytorch" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/pytorch/archive/v{{ version }}.tar.gz
  sha256: b76d61aaa8fc18b928ca3c910c398687be08f5661d6615884c4faba3e8742a26

build:
  number: 0
  features:
    - blas_{{ blas_impl }}
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
  host:
    - python
    - pip
    - numpy
    - pyyaml
    - cffi
    - openblas
  run:
    - python
    - numpy
    - cffi
    - openblas

test:
  imports:
    - torch

about:
  home: http://pytorch.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Tensors and Dynamic neural networks in Python with strong GPU acceleration'
  description: |
    PyTorch is a Python package that provides two high-level features:
    - Tensor computation (like NumPy) with strong GPU acceleration
    - Deep neural networks built on a tape-based autograd system
    
    You can reuse your favorite Python packages such as NumPy, SciPy and Cython
    to extend PyTorch when needed.

    We are in an early-release beta. Expect some adventures and rough edges. 
  doc_url: http://pytorch.org/docs/
  dev_url: https://github.com/pytorch/pytorch

extra:
  recipe-maintainers:
    - dougalsutherland
    - soumith
