{% set name = "or-tools" %}
{% set version = "7.3" %}

package:
  name: ortools
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/google/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b87922b75bbcce9b2ab5da0221751a3c8c0bff54b2a1eafa951dbf70722a640e
  #patches:
  #  - use_conda_dependencies.patch
  #  - use_conda_python_dependencies.patch

build:
  number: 0
  skip: True  # [(osx or win)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf 2.69
    - automake 1.15
    - bison 3.0.*
    - cmake
    - curl
    - flex 2.6.*
    - git
    - patchelf 0.10
    - swig

  host:
    - gflags 2.2.2
    - glog 0.4.0
    - protobuf 3.9.0
    - coincbc 2.10.*

    #- help2man 1.47.*
    #- libtool 2.4.*
    #- pcre 8.*
    #- python
    #- protobuf 3.0.*
    #- setuptools
    #- sparsehash 2.0.*
    #- swig 3.0.*
    #- texinfo
    #- texlive-core
    #- unzip

  run:
    #- coincbc 2.9.*
    #- gflags 2.1.*
    #- pcre 8.*
    #- protobuf 3.0.*
    #- python
    #- sparsehash 2.0.*

test:
  imports:
    - ortools
    - ortools.algorithms
    - ortools.constraint_solver
    - ortools.graph
    - ortools.linear_solver

about:
  home: https://developers.google.com/optimization/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE-2.0.txt
  summary: 'Google Optimization Tools is a fast and portable software suite for solving combinatorial optimization problems'

  description: |
  doc_url: https://developers.google.com/optimization/introduction/using
  dev_url: https://github.com/google/or-tools

extra:
  recipe-maintainers:
    - sodre
