{% set name = "Pyrogram" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95beff6eb1dbee38a96405a0d6600fda5ccbc8a9f29e693543f45b3a2ef0245b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - async-lru >=1.0.2,<2
    - pyaes >=1.6.1,<1.7
    - pysocks >=1.7.1,<2
    - tgcrypto >=1.2.0,<2

test:
  imports:
    - pyrogram
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyrogram/pyrogram
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.lesser
  summary: 'Telegram MTProto API Client Library and Framework for Python'

  doc_url: https://docs.pyrogram.org/
  dev_url: https://github.com/pyrogram/pyrogram

extra:
  recipe-maintainers:
    - sodre
