# ########################################################################### #
# NOTE: If you change this file, you must regenerate the feedstock.           #
#   - conda smithy regenerate                                                 #
#   - @conda-forge-admin, please rerender                                     #
# ########################################################################### #

# Select the darknet variants that we are building
# The variant names, and versions come from the _darknet_mutex conda-package
darknet_variant_str:
  - cpu
# One-hot-encoding of the variant selection above
cpu:
  - true
gpu:
  - false

#
# Tie the variables together
zip_keys:
  -
    - darknet_variant_str
    - cpu
    - gpu
